apiVersion: "v1"
kind: "Pod"
metadata:
  annotations: {}
  # this label lets jenkins know that this pod is needs to be managed
  # all k8s slave pods must have this label
  labels:
    jenkins: "slave"
spec:
  containers:
    # container for building and pushing docker images
    # pre-configured with ala-artifactory credentials
  - name: "docker" # this name is used inside the pipeline as a label for the container
    image: "ala-artifactory.wrs.com/docker-devstar/docker:1.0.0"
    imagePullPolicy: "IfNotPresent"
    # resource limits should be set when usage is known
    resources:
      limits: {}
      requests: {}
    securityContext:
      privileged: false
    tty: true
    # cat command keeps container alive
    command: ["cat"]
    volumeMounts:
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volume"
      readOnly: false
    # this container needs to use the shared docker.sock from the k8s node
    - mountPath: "/var/run/docker.sock"
      name: "docker-sock"
      readOnly: true
    workingDir: "/home/jenkins/agent"
  # default container for communication with the jenkins master
  # always included in k8s slave pods
  - name: "jnlp"
    image: "jenkins/jnlp-slave:alpine"
    volumeMounts:
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volume"
      readOnly: false
  restartPolicy: "Never"
  volumes:
  # this volume shares the job workspace between containers
  - emptyDir:
      medium: ""
    name: "workspace-volume"
  # this volume shares the docker.sock for Docker builds
  - name: "docker-sock"
    hostPath:
      path: "/var/run/docker.sock"
